### ISSUE TITLE
Specifying watermark as a relative path via the command line didn't work

### ISSUE THREAD

**Issue by platisd** [platisd/eely#4]
It's looking for the watermarks inside the `course-plan` (or whatever) directory

**Comment by kaan36875** [comment]
Hello, I think I've solved it.

**Comment by platisd** [comment]
Hi, thanks for looking into it.
No, I don't think #5 would solve this.
The idea is that we'd like the users to be able to specify a relative path to the watermark.
The problem is that this path is then placed into config and becomes invalid because the config may be in another location. 
The easiest solution is if a watermark path is supplied as an argument, if it's relative, turn it into an absolute and then do everything else as it's currently done.
